- package-lock.json
- package.json
- src/server/app.js
- src/server/config/routes.js
- src/server/controllers/mot-test/mot-test.js
- src/server/views/macros/elements/textarea.njk
- src/server/views/prototypes/mot-test/comment/edit.njk
- src/server/views/prototypes/mot-test/comment/index.njk
- src/server/views/prototypes/mot-test/comment/partials/form-errors.njk
- src/server/views/prototypes/mot-test/comment/remove.njk
- src/server/views/prototypes/mot-test/index.njk
- Tester comments - edit user journey
- Tester comments - remove user journey
- Added connect-flash node middleware
> Tester comments edit and remove

- src/server/views/prototypes/brake-test-review/index.njk
- src/server/views/prototypes/index.njk
this is not done in production ready code. done by a designer.
> added brake test review page to prototypes

- package-lock.json
- src/assets/js/dvsa-mts-legacy/modules/mot-test-search-date-range-results/index.js
- src/assets/js/dvsa-mts-legacy/modules/mot-test-search-vts-results/index.js
- src/server/views/library/content/progressive-disclosure.njk
Updated javascript typos to fix errors and also changed "Hidden Text" in library to be called "Progressive Disclosure" as it is more meaningful.
**Before submitting a PR, ensure** -
> Updated typos to fix javascript errors

- src/server/views/prototypes/index.njk
***
- [] Another FED has reviewed.
***
Minor content updates to prototypes
> Updated prototypes content

- src/assets/js/development/modules/index.js
- src/server/config/routes.js
- src/server/controllers/site-review/initViewData.js
- src/server/controllers/site-review/site-review.js
- src/server/controllers/site-review/validators/validation.js
- src/server/helpers/prism-code.js
- src/server/views/prototypes/site-review/choose-section/index.njk
- src/server/views/prototypes/site-review/enter-details/index.njk
- src/server/views/prototypes/site-review/index.njk
- src/server/views/prototypes/site-review/people.njk
All changes made since the branch was created from 'express-updates' branch:
- Added validation for last page. An extra field is displayed when declaring 'two examiners' - when shown, this field is now mandatory.
- Other fields entered persist in view
- Minor copy changes
- No selection by default on Outcomes
Checked it and all runs locally.
> Manually rebased validation changes branch

- src/server/config/routes.js
- src/server/controllers/site-review/helpers/populateActivity.js
- src/server/controllers/site-review/initViewData.js
- src/server/controllers/site-review/site-review.js
- src/server/controllers/site-review/validators/validation.js
- src/server/views/prototypes/site-review/assessment/activity/index.njk
- src/server/views/prototypes/site-review/assessment/compliance/index.njk
- src/server/views/prototypes/site-review/assessment/management-and-quality/index.njk
- src/server/views/prototypes/site-review/assessment/people/index.njk
- src/server/views/prototypes/site-review/assessment/premises/index.njk
- src/server/views/prototypes/site-review/choose-section/index.njk
- src/server/views/prototypes/site-review/enter-details/index.njk
- src/server/views/prototypes/site-review/index.njk
- src/server/views/prototypes/site-review/summary/index.njk
Site review updates - added other textarea functionality to the activity page / summary
Minor content updates to assessment guidance in site review
Minor content updates to site review journey
***
- [ 👎 ] You haven't added inline styles.
- [ ;) ] You haven't added inline JavaScript.
***
- Add other activity functionality 
- Minor content updates
> Added comment to activity.

- dist/server/controllers/site-review/validators/validation.js
- src/server/views/prototypes/site-review/AE-view/index.njk
- src/server/views/prototypes/site-review/AE-view/view-details.njk
- src/server/views/prototypes/site-review/VE-view.njk
- src/server/views/prototypes/site-review/assessment/activity/index.njk
- src/server/views/prototypes/site-review/index.njk
> Feature site review update

- src/server/views/prototypes/index.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-confirmation.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-preview.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-review.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-user.njk
- src/server/views/prototypes/mts-messages/scheme/index.njk
- src/server/views/prototypes/mts-messages/scheme/remove-message-confirmation.njk
- src/server/views/prototypes/mts-messages/scheme/remove-message.njk
- src/server/views/prototypes/mts-messages/trade/index.njk
- src/server/views/prototypes/mts-messages/trade/notification-news-from-unread.njk
- src/server/views/prototypes/mts-messages/trade/notification-sn-acknowledge.njk
- src/server/views/prototypes/mts-messages/trade/notifications-archived-trade-user.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-news-read.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-nothing.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-sn-acknowledged-system-message.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-sn-acknowledged.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-sn-news.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-sn-read.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-sn.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user.njk
> Mts messages edits

- .gitignore
- src/server/views/prototypes/site-review/v5-resume/enter-details.njk
- src/server/views/prototypes/site-review/v5/enter-details.njk
> Deleted panel for second VE's ID

- src/server/views/prototypes/site-review/index.njk
- src/server/views/prototypes/site-review/v5-resume/enter-details.njk
- src/server/views/prototypes/site-review/v5/AE-view-view-details-improve.njk
- src/server/views/prototypes/site-review/v5/AE-view-view-details-unsatisfactory.njk
- src/server/views/prototypes/site-review/v5/AE-view-view-details-v2.njk
- src/server/views/prototypes/site-review/v5/enter-details.njk
- src/server/views/prototypes/site-review/v5/index.njk
> Added content to AE view

- src/server/views/prototypes/site-review/index.njk
- src/server/views/prototypes/site-review/v5/AE-view-service-reports.njk
- src/server/views/prototypes/site-review/v5/index.njk
> Added Service Reports page

- src/assets/scss/mts/modules/action-panel/_action-panel.scss
- src/assets/scss/mts/modules/defect-summary/_defect-summary.scss
- src/server/controllers/site-review/initViewData.js
- src/server/controllers/site-review/site-review.js
- src/server/controllers/site-review/validators/validation.js
- src/server/views/prototypes/index.njk
- src/server/views/prototypes/site-review/VE-view.njk
- src/server/views/prototypes/site-review/abort/index.njk
- src/server/views/prototypes/site-review/assessment/activity/index.njk
- src/server/views/prototypes/site-review/assessment/compliance/index.njk
- src/server/views/prototypes/site-review/assessment/management-and-quality/index.njk
- src/server/views/prototypes/site-review/assessment/people/index.njk
- src/server/views/prototypes/site-review/assessment/premises/index.njk
- src/server/views/prototypes/site-review/choose-section/index.njk
- src/server/views/prototypes/site-review/enter-details/index.njk
- src/server/views/prototypes/site-review/index.njk
- src/server/views/prototypes/site-review/saved/index.njk
- src/server/views/prototypes/site-review/summary/index.njk
- src/server/views/prototypes/site-review/v4/index.njk
> Site review markup updates

- src/server/views/prototypes/site-review/v5-resume/summary.njk
- src/server/views/prototypes/site-review/v5/AE-view-VTS-overview.njk
- src/server/views/prototypes/site-review/v5/VE-view-VTS-overview.njk
- src/server/views/prototypes/site-review/v5/summary.njk
> Content update. Changed 'risk rank" to 'VTS RAG'

- src/server/views/prototypes/mts-messages/homepage/index-dashboard-006.njk
- src/server/views/prototypes/mts-messages/homepage/index-dashboard-007.njk
- src/server/views/prototypes/mts-messages/homepage/index-dashboard-008.njk
- src/server/views/prototypes/mts-messages/homepage/index.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-002.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-003.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-004.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-005.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-006.njk
- src/server/views/prototypes/mts-messages/trade/notifications-inbox-trade-user-007.njk
***
New pages for the homepage design and trade inbox.
> homepage designs and alternative inbox content layouts.

- src/assets/js/development/modules/mts-messages/filter-messages.js
- src/assets/js/development/modules/mts-messages/index.js
- src/assets/js/shared/misc/get-query.js
- src/assets/scss/gds/template/partials/_accessibility.scss
- src/server/views/prototypes/mts-messages/homepage/index-dashboard-008.njk
- src/server/views/prototypes/mts-messages/homepage/index-dashboard-010.njk
Support for filtering Special Notices in query string:
?filter=sn
Only works (for now) with Special Notices as this will be linked from the Home page
> Enable filtering using query string:  ?filter=sn in URL on Inbox view

- src/server/views/prototypes/mts-messages/scheme/create-message-news-review.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-sn-content.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-sn-review.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-type.njk
> scheme user create amends.

- src/server/controllers/site-review/validators/validation.js
> Fix for a bug in site review journey

- src/server/views/prototypes/mts-messages/scheme/create-message-confirmation.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-news-content.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-sn-content.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-sn-review.njk
- src/server/views/prototypes/mts-messages/scheme/create-message-type.njk
- src/server/views/prototypes/mts-messages/scheme/index.njk
- src/server/views/prototypes/mts-messages/scheme/notification-draft-removed.njk
- src/server/views/prototypes/mts-messages/scheme/notifications-archived-scheme-user.njk
- src/server/views/prototypes/mts-messages/scheme/notifications-draft-scheme-user.njk
- src/server/views/prototypes/mts-messages/scheme/notifications-removed-scheme-user.njk
- src/server/views/prototypes/mts-messages/scheme/remove-message-confirmation.njk
- src/server/views/prototypes/mts-messages/scheme/remove-message.njk
***
Content changes and new pages mainly for Scheme user create message and their inbox.
> Mts messaging scheme user tickets

- src/server/views/prototypes/correct-test-record/index.njk
- src/server/views/prototypes/correct-test-record/v1/MOT-test-complete.njk
- src/server/views/prototypes/correct-test-record/v1/confirm-vehicle-details.njk
- src/server/views/prototypes/correct-test-record/v1/enter-test-results.njk
- src/server/views/prototypes/correct-test-record/v1/home-page.njk
- src/server/views/prototypes/correct-test-record/v1/mot-test-started.njk
- src/server/views/prototypes/correct-test-record/v1/review-test.njk
- src/server/views/prototypes/correct-test-record/v1/test-in-progress.njk
- src/server/views/prototypes/correct-test-record/v1/testing-information.njk
- src/server/views/prototypes/correct-test-record/v1/vehicle-results.njk
- src/server/views/prototypes/correct-test-record/v1/vehicle-search.njk
- src/server/views/prototypes/correct-test-record/v2/MOT-test-complete.njk
- src/server/views/prototypes/correct-test-record/v2/confirm-vehicle-details.njk
- src/server/views/prototypes/correct-test-record/v2/enter-test-results.njk
- src/server/views/prototypes/correct-test-record/v2/home-page.njk
- src/server/views/prototypes/correct-test-record/v2/mot-test-started.njk
- src/server/views/prototypes/correct-test-record/v2/review-test.njk
- src/server/views/prototypes/correct-test-record/v2/test-in-progress.njk
- src/server/views/prototypes/correct-test-record/v2/testing-information.njk
- src/server/views/prototypes/correct-test-record/v2/vehicle-results.njk
- src/server/views/prototypes/correct-test-record/v2/vehicle-search.njk
This is a new version of the MOT testing journey. With two main journeys with logos and without logos.
The only thing that is missing is a link to it from the prototype index page.
***
***
> Test record management

- src/assets/scss/modules/utils/_utils.scss
- src/assets/scss/modules/utils/partials/_u-disable-pointer-events.scss
- src/assets/scss/mts/modules/utils/partials/_misc.scss
- src/server/views/prototypes/site-review/choose-section/index.njk
> Moved IOS pointer events fix to utils scss partial

- src/server/views/prototypes/site-review/v5/AE-view-VTS-overview.njk
- src/server/views/prototypes/site-review/v5/VE-view-VTS-overview.njk
- src/server/views/prototypes/site-review/v5/assessment-activity-choose-reason.njk
- src/server/views/prototypes/site-review/v5/assessment-activity-enter-mot-number.njk
- src/server/views/prototypes/site-review/v5/your-profile.njk
> Feature site review activity

- src/assets/scss/modules/utils/partials/_u-disable-pointer-events.scss
> Hard coding colour to default body colour

- src/assets/scss/mts/modules/_modules.scss
- src/assets/scss/mts/modules/message-notification/_message-notification.scss
- src/assets/scss/mts/modules/messages/_messages.scss
- src/server/config/routes.js
- src/server/controllers/mts-messages/data.js
- src/server/controllers/mts-messages/helpers/filters.js
- src/server/controllers/mts-messages/middleware/index.js
- src/server/controllers/mts-messages/middleware/setNotificationCounts.js
- src/server/controllers/mts-messages/middleware/setupMessages.js
- src/server/controllers/mts-messages/router.js
- src/server/views/prototypes/messages/homepage/index.njk
- src/server/views/prototypes/messages/inbox/index.njk
- src/server/views/prototypes/mts-messages/index.njk
Updated MTS middleware logic
new routes / template files for MTS messages homepage created
message-notification CSS pattern created
> Mts-messaging home page prototype

- src/server/views/prototypes/site-review/v5/VE-view-VTS-overview.njk
- src/server/views/prototypes/site-review/v5/VE-view-site-review-summary.njk
- src/server/views/prototypes/site-review/v5/abort-are-you-sure.njk
- src/server/views/prototypes/site-review/v5/assessment-activity.njk
- src/server/views/prototypes/site-review/v5/assessment-compliance.njk
- src/server/views/prototypes/site-review/v5/assessment-management-and-quality.njk
- src/server/views/prototypes/site-review/v5/assessment-people.njk
- src/server/views/prototypes/site-review/v5/assessment-premises.njk
- src/server/views/prototypes/site-review/v5/choose-section-premises-done.njk
- src/server/views/prototypes/site-review/v5/choose-section.njk
- src/server/views/prototypes/site-review/v5/enter-details.njk
- src/server/views/prototypes/site-review/v5/enter-event-details.njk
- src/server/views/prototypes/site-review/v5/summary.njk
Breadcrumb updates to site review V5
> Breadcrumbs update to V5 site review

- src/server/config/routes.js
- src/server/controllers/site-review/site-review.js
- src/server/views/prototypes/site-review/v5/assessment-activity-choose-reason.njk
- src/server/views/prototypes/site-review/v5/assessment-activity-enter-mot-number.njk
- src/server/views/prototypes/site-review/v5/assessment-activity.njk
Minor express logic for site review V5
Minor content / breadcrumbs updates
> Site review v5 routing

- src/server/views/prototypes/site-review/VE-view.njk
- src/server/views/prototypes/site-review/abort/index.njk
- src/server/views/prototypes/site-review/assessment/activity/index.njk
- src/server/views/prototypes/site-review/assessment/compliance/index.njk
- src/server/views/prototypes/site-review/assessment/management-and-quality/index.njk
- src/server/views/prototypes/site-review/assessment/people/index.njk
- src/server/views/prototypes/site-review/assessment/premises/index.njk
- src/server/views/prototypes/site-review/choose-section/index.njk
- src/server/views/prototypes/site-review/enter-details/index.njk
- src/server/views/prototypes/site-review/summary/index.njk
Breadcrumbs updated for functional site review prototype.
> Breadcrumbs updated for functional prototype site review

- package-lock.json
- package.json
- src/assets/js/development/modules/autocomplete/index.js
- src/assets/js/development/modules/index.js
- src/assets/scss/gds/elements/_elements.scss
- src/assets/scss/gds/elements/partials/_autocomplete.scss
- src/assets/scss/modules/_modules.scss
- src/assets/scss/modules/autocomplete/_autocomplete.scss
- src/server/views/prototypes/autocomplete/index.njk
> Autocomplete test

- src/assets/js/development/modules/autocomplete/index.js
- src/assets/scss/mts/modules/message-notification/_message-notification.scss
- src/server/views/prototypes/messages/homepage/index.njk
- src/server/views/prototypes/mts-messages/index.njk
> Further CSS updates to MTS-homepage view

- src/server/views/prototypes/site-review/v5/AE-view-service-reports.njk
> Further breadcrumb changes

- src/server/views/prototypes/site-review/index.njk
- src/server/views/prototypes/site-review/v5-resume/index.njk
- src/server/views/prototypes/site-review/v5/VE-view-VTS-overview.njk
- src/server/views/prototypes/site-review/v5/assessment-activity-enter-mot-number.njk
- src/server/views/prototypes/site-review/v5/check-event-details.njk
- src/server/views/prototypes/site-review/v5/choose-section-premises-done.njk
- src/server/views/prototypes/site-review/v5/enter-event-details.njk
- src/server/views/prototypes/site-review/v5/index.njk
- src/server/views/prototypes/site-review/v5/summary.njk
> Updated several screens

- src/assets/scss/mts/modules/_modules.scss
- src/assets/scss/mts/modules/badge/_badge.scss
- src/server/views/library/mts/defect-summary.njk
Added prototype defect summary table
> Added prototype defect summary table

- src/assets/scss/mts/modules/_modules.scss
- src/assets/scss/mts/modules/messages/_markdown.scss
+ Add new _markdown.scss file to house the styling used to preview special notices
+ Add this new file to _module.scss
***
***
> Add styling for markdown

- src/server/views/prototypes/vsi-during-test/front-exterior-checks/add-advisory.njk
- src/server/views/prototypes/vsi-during-test/front-exterior-checks/front-exterior-checks-4.njk
- src/server/views/prototypes/vsi-during-test/inspection/index.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-2.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-3.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-4.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-5.njk
- src/server/views/prototypes/vsi-during-test/interior-checks/interior-checks-3.njk
> Minor route / content updates to vsi journy

- src/server/config/routes.js
- src/server/controllers/vsi-during-test/vsi-during-test.js
- src/server/views/prototypes/vsi-during-test/advice/index.njk
- src/server/views/prototypes/vsi-during-test/inspection/index.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-2.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-3.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-4.njk
- src/server/views/prototypes/vsi-during-test/inspection/inspection-5.njk
- src/server/views/prototypes/vsi-during-test/test-started.njk
> Vsi update progressive disclosure

- src/assets/js/dvsa-mts/modules/mts-login/index.js
- src/server/views/prototypes/mts-login/index.njk
Updated functionality on mts-login.js
> Updated functionality on mts-login.js

- src/server/views/prototypes/site-review/v5/AE-view-view-details-improve.njk
- src/server/views/prototypes/site-review/v5/AE-view-view-details-unsatisfactory.njk
- src/server/views/prototypes/site-review/v5/AE-view-view-details.njk
Removed duplicate row instances in site review
> removed duplicate table row in site review journey

- src/server/views/prototypes/site-review/v5/summary.njk
Minor content updates to site review summary
> re-order of content in site review summary

- src/server/views/prototypes/site-review/index.njk
- src/server/views/prototypes/site-review/v5/VE-view-VTS-overview.njk
- src/server/views/prototypes/site-review/v5/check-event-details.njk
- src/server/views/prototypes/site-review/v5/index.njk
> Content changes to VTS overview and event page

- src/server/views/prototypes/correct-test-record/index.njk
- src/server/views/prototypes/correct-test-record/v1a/MOT-test-complete.njk
- src/server/views/prototypes/correct-test-record/v1a/confirm-vehicle-details.njk
- src/server/views/prototypes/correct-test-record/v1a/enter-test-results.njk
- src/server/views/prototypes/correct-test-record/v1a/home-page.njk
- src/server/views/prototypes/correct-test-record/v1a/mot-test-started.njk
- src/server/views/prototypes/correct-test-record/v1a/review-test.njk
- src/server/views/prototypes/correct-test-record/v1a/test-in-progress.njk
- src/server/views/prototypes/correct-test-record/v1a/testing-information.njk
- src/server/views/prototypes/correct-test-record/v1a/vehicle-results.njk
- src/server/views/prototypes/correct-test-record/v1a/vehicle-search.njk
- src/server/views/prototypes/correct-test-record/v2a/MOT-test-complete.njk
- src/server/views/prototypes/correct-test-record/v2a/confirm-vehicle-details.njk
- src/server/views/prototypes/correct-test-record/v2a/enter-test-results.njk
- src/server/views/prototypes/correct-test-record/v2a/home-page.njk
- src/server/views/prototypes/correct-test-record/v2a/mot-test-started.njk
- src/server/views/prototypes/correct-test-record/v2a/review-test.njk
- src/server/views/prototypes/correct-test-record/v2a/test-in-progress.njk
- src/server/views/prototypes/correct-test-record/v2a/testing-information.njk
- src/server/views/prototypes/correct-test-record/v2a/vehicle-results.njk
- src/server/views/prototypes/correct-test-record/v2a/vehicle-search.njk
- src/server/views/prototypes/recalls/MOTH-version/MOTH-page.njk
- src/server/views/prototypes/recalls/V2/results-page.njk
- src/server/views/prototypes/recalls/index.njk
> Index page tidy up + test record alterations

- package-lock.json
- package.json
- src/assets/scss/modules/utils/partials/_u-disable-pointer-events.scss
Adding variable for link colour (this class is to override iOS link behaviour)
> Css util amend

- src/server/views/prototypes/recalls/Component-version/Start-page.njk
- src/server/views/prototypes/recalls/Component-version/component-make.njk
- src/server/views/prototypes/recalls/Component-version/component-model.njk
- src/server/views/prototypes/recalls/Component-version/component-results.njk
- src/server/views/prototypes/recalls/Component-version/type-of-recall.njk
- src/server/views/prototypes/recalls/Error-messages/error-type-of-recall.njk
- src/server/views/prototypes/recalls/Error-messages/error-vehicle-age.njk
- src/server/views/prototypes/recalls/Error-messages/error-vehicle-make.njk
- src/server/views/prototypes/recalls/Error-messages/error-vehicle-model.njk
- src/server/views/prototypes/recalls/Error-messages/error-vehicle-type.njk
- src/server/views/prototypes/recalls/MOTH-version/MOTH-page.njk
- src/server/views/prototypes/recalls/V1/results-page.njk
- src/server/views/prototypes/recalls/V1/vehicle-make.njk
- src/server/views/prototypes/recalls/V1/vehicle-type.njk
- src/server/views/prototypes/recalls/V3/Start-page.njk
- src/server/views/prototypes/recalls/V3/component-make.njk
- src/server/views/prototypes/recalls/V3/component-model.njk
- src/server/views/prototypes/recalls/V3/component-results.njk
- src/server/views/prototypes/recalls/V3/results-page.njk
- src/server/views/prototypes/recalls/V3/type-of-recall.njk
- src/server/views/prototypes/recalls/V3/vehicle-make.njk
- src/server/views/prototypes/recalls/V3/vehicle-model.njk
- src/server/views/prototypes/recalls/V3/year-of-manufactuer.njk
- src/server/views/prototypes/recalls/index.njk
> Recalls final changes

- src/server/views/prototypes/compare-tests/v2/assess-difference-defect.njk
- src/server/views/prototypes/compare-tests/v2/assess-difference-odometer.njk
- src/server/views/prototypes/compare-tests/v2/change-outcome.njk
- src/server/views/prototypes/compare-tests/v2/check-answers-v4-DAR.njk
- src/server/views/prototypes/compare-tests/v2/check-answers-v4.njk
- src/server/views/prototypes/compare-tests/v2/compare-brakes.njk
- src/server/views/prototypes/compare-tests/v2/compare-defects-differences.njk
- src/server/views/prototypes/compare-tests/v2/compare-defects-mark-difference.njk
- src/server/views/prototypes/compare-tests/v2/compare-defects-marked.njk
- src/server/views/prototypes/compare-tests/v2/compare-defects.njk
- src/server/views/prototypes/compare-tests/v2/compare-odometer-marked.njk
- src/server/views/prototypes/compare-tests/v2/compare-odometer.njk
- src/server/views/prototypes/compare-tests/v2/test-comparison-v4-brakes-reviewed.njk
- src/server/views/prototypes/compare-tests/v2/test-comparison-v4-defects-reviewed.njk
- src/server/views/prototypes/compare-tests/v2/test-comparison-v4-odometer-reviewed.njk
- src/server/views/prototypes/compare-tests/v2/test-comparison-v4.njk
> Updated screens for usability testing

- src/server/views/prototypes/correct-test-record/v1a/MOT-test-complete.njk
- src/server/views/prototypes/correct-test-record/v1a/confirm-vehicle-details.njk
- src/server/views/prototypes/correct-test-record/v1a/enter-test-results.njk
- src/server/views/prototypes/correct-test-record/v1a/mot-test-started.njk
- src/server/views/prototypes/correct-test-record/v1a/review-test.njk
- src/server/views/prototypes/correct-test-record/v1a/test-in-progress.njk
- src/server/views/prototypes/correct-test-record/v1a/vehicle-results.njk
> new vehicle for testing

- dist/assets/javascripts/development.bundle.js
- dist/assets/javascripts/dvsa-manuals.bundle.js
- dist/assets/javascripts/dvsa-mts-legacy.bundle.js
- dist/assets/javascripts/dvsa-mts.bundle.js
- dist/assets/javascripts/dvsa.bundle.js
- dist/assets/javascripts/vendor.bundle.js
- dist/assets/stylesheets/development.css
- dist/assets/stylesheets/styles.css
- src/assets/scss/mts/modules/action-panel/_action-panel.scss
- src/assets/scss/mts/modules/table-summary/_table-summary.scss
Changes to summary table for SR journey
> Feature bl 8865 sr styles

- src/server/views/prototypes/recalls/Component-version/component-make.njk
- src/server/views/prototypes/recalls/Component-version/component-model.njk
- src/server/views/prototypes/recalls/V3/Start-page.njk
- src/server/views/prototypes/recalls/V3/component-make.njk
- src/server/views/prototypes/recalls/V3/type-of-recall.njk
- src/server/views/prototypes/recalls/V3/vehicle-model.njk
- src/server/views/prototypes/recalls/index.njk
- src/server/views/prototypes/recalls/no-recalls/no-component-recall.njk
- src/server/views/prototypes/recalls/no-recalls/no-recalls.njk
- src/server/views/prototypes/recalls/no-recalls/vehicle-make.njk
> Recall changes for sprint

- src/server/views/prototypes/correct-test-record/v1a/confirm-vehicle-details.njk
Tiny pull request for the testing tomorrow. 
***
** Style **
***
> routes corrected

- dist/assets/javascripts/development.bundle.js
- dist/assets/javascripts/dvsa-manuals.bundle.js
- dist/assets/javascripts/dvsa-mts-legacy.bundle.js
- dist/assets/javascripts/dvsa-mts.bundle.js
- dist/assets/javascripts/dvsa.bundle.js
- dist/assets/javascripts/vendor.bundle.js
- dist/assets/stylesheets/development.css
- dist/assets/stylesheets/styles.css
- src/assets/misc/manifest-motr.json
New manifest for MOTR - new icon paths
> New manifest for motr

- src/assets/scss/gds/elements/partials/_elements-typography.scss
- src/assets/scss/gds/elements/partials/_icons.scss
- src/server/views/library/components/index.njk
- src/server/views/library/components/notices.njk
- src/server/views/library/content/index.njk
- src/server/views/library/layout/index.njk
- src/server/views/library/misc/index.njk
- src/server/views/library/mts/index.njk
- src/server/views/library/mts/notice-messages.njk
- src/server/views/prototypes/recalls/V3/type-of-recall.njk
Icons and new GDS Notices in front-end library
> GDS Icons  +

- src/assets/scss/gds/elements/partials/_elements-typography.scss
- src/assets/scss/gds/elements/partials/_icons.scss
- src/assets/scss/modules/accordion/_accordion.scss
- src/server/views/library/components/accordions.njk
- src/server/views/library/components/index.njk
- src/server/views/library/components/notices.njk
- src/server/views/library/content/index.njk
- src/server/views/library/layout/index.njk
- src/server/views/library/misc/index.njk
- src/server/views/library/mts/index.njk
- src/server/views/library/mts/notice-messages.njk
- src/server/views/prototypes/recalls/V3/type-of-recall.njk
Added accordion to component library
> Added accordion to component library

- src/server/views/prototypes/vts-changes/approved/index.njk
- src/server/views/prototypes/vts-changes/change-notice.njk
- src/server/views/prototypes/vts-changes/classes/index.njk
- src/server/views/prototypes/vts-changes/confirmation/index.njk
- src/server/views/prototypes/vts-changes/declaration.njk
- src/server/views/prototypes/vts-changes/layout/index.njk
- src/server/views/prototypes/vts-changes/short-summary/index.njk
- src/server/views/prototypes/vts-changes/start.njk
- src/server/views/prototypes/vts-changes/summary/index.njk
- src/server/views/prototypes/vts-changes/type/index.njk
- src/server/views/prototypes/vts-changes/unapproved-notice.njk
> Back button changes

- src/server/views/prototypes/recalls/Component-version/Start-page.njk
- src/server/views/prototypes/recalls/Component-version/component-make.njk
- src/server/views/prototypes/recalls/Component-version/component-model.njk
- src/server/views/prototypes/recalls/Component-version/type-of-recall.njk
- src/server/views/prototypes/recalls/V3/Start-page.njk
- src/server/views/prototypes/recalls/V3/vehicle-make.njk
- src/server/views/prototypes/recalls/V3/vehicle-model.njk
- src/server/views/prototypes/recalls/index.njk
- src/server/views/prototypes/recalls/no-recalls/no-component-recall.njk
- src/server/views/prototypes/recalls/no-recalls/no-recalls.njk
Content changes for GDS demo Thursday morning. 
***
** Style **
***
> content changes for GDS demo

- src/assets/js/shared/gds/modules/cookie-message/index.js
> BL-9011: set expiry to be int timestamp rather than string

- package-lock.json
- src/server/views/prototypes/vts-changes/start.njk
- src/server/views/prototypes/vts-changes/v3/start.njk
> Vts changes content

- src/server/views/prototypes/compare-tests/index.njk
- src/server/views/prototypes/compare-tests/v4/check-answers-outcome.njk
- src/server/views/prototypes/compare-tests/v4/check-answers.njk
- src/server/views/prototypes/compare-tests/v4/compare-brakes-v2.njk
- src/server/views/prototypes/compare-tests/v4/compare-brakes-v3.njk
- src/server/views/prototypes/compare-tests/v4/compare-brakes-v4.njk
- src/server/views/prototypes/compare-tests/v4/compare-brakes.njk
- src/server/views/prototypes/compare-tests/v4/punishment.njk
- src/server/views/prototypes/compare-tests/v4/saved.njk
- src/server/views/prototypes/compare-tests/v4/test-comparison-brakes-reviewed.njk
- src/server/views/prototypes/compare-tests/v4/test-comparison-defects-reviewed.njk
- src/server/views/prototypes/compare-tests/v4/test-comparison.njk
> Updated brake test results comparison after user feedback

- src/server/views/prototypes/vts-changes/approved/index.njk
- src/server/views/prototypes/vts-changes/change-notice.njk
- src/server/views/prototypes/vts-changes/classes/index.njk
- src/server/views/prototypes/vts-changes/declaration.njk
- src/server/views/prototypes/vts-changes/layout/index.njk
- src/server/views/prototypes/vts-changes/short-summary/index.njk
- src/server/views/prototypes/vts-changes/start.njk
- src/server/views/prototypes/vts-changes/type/index.njk
- src/server/views/prototypes/vts-changes/unapproved-notice.njk
> links to 'Return to VTS Overview' added

- src/assets/js/shared/gds/modules/cookie-message/index.js
***
- [ X ] This solution is documented and approved against ACs in the Jira ticket.
- [ X] Branch name include Jira ticket ref.
- [X ] `npm run start-dev` runs successfully with changes.
** Style **
- [ X ] Console logs are removed.
- [ X ] Code has been indented for readability.
- [X ] You haven't added inline styles.
- [ X] You haven't added inline JavaScript.
***
> Remove and overwrite invalid Cookies Stored as a String - BL-9011

- src/assets/js/dvsa-mts-legacy/third-party/bootstrap-popover/index.js
- src/assets/js/dvsa-mts-legacy/third-party/bootstrap-tooltip/index.js
- src/server/views/prototypes/compare-tests/index.njk
- src/server/views/prototypes/compare-tests/v4/compare-brakes-v5.njk
- src/server/views/prototypes/compare-tests/v4/test-comparison.njk
> Removed percentages from brake test results v4

- src/assets/js/dvsa-mts/modules/filter-messages/filter-messages.js
***
**Before submitting a PR for PRODUCTION in MTS, consider ** - 
** Style **
* Mark done with an ❎ *
***
> Fixed Inbox filters for IE and Edge

- src/server/views/prototypes/ae-application-tool/index.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-details-1.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-details.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search-1.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search-results-1.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search-results.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search.njk
- src/server/views/prototypes/ae-application-tool/v1/index.njk
- src/server/views/prototypes/index.njk
***
**Before submitting a PR for PRODUCTION in MTS, consider ** - 
** Style **
* Mark done with an ❎ *
***
> Initial screens for AE applicant hotlist checking tool

- src/server/views/prototypes/ae-application-tool/index.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-details-1.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-details-2.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search-1.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search-results-1.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search-results.njk
- src/server/views/prototypes/ae-application-tool/v1/applicant-search.njk
- src/server/views/prototypes/ae-application-tool/v1/index-1.njk
Prototype journeys for AE Application Tool
> Added 2nd journey for user testing & updates to journey one

- src/server/views/prototypes/first-use-date/from-date.njk
- src/server/views/prototypes/first-use-date/index.njk
- src/server/views/prototypes/first-use-date/pre-date.njk
- src/server/views/prototypes/index.njk
***
**Before submitting a PR for PRODUCTION in MTS, consider ** - 
** Style **
* Mark done with an ❎ *
***
> Added 'First use date' stopper screen

- src/assets/scss/mts/modules/eu-defect/_eu-defect.scss
> Defect button fix

- dist/assets/javascripts/development.bundle.js
- dist/assets/javascripts/dvsa-manuals.bundle.js
- dist/assets/javascripts/dvsa-mts-legacy.bundle.js
- dist/assets/javascripts/dvsa-mts.bundle.js
- dist/assets/javascripts/dvsa.bundle.js
- dist/assets/javascripts/vendor.bundle.js
- dist/assets/stylesheets/development.css
- dist/assets/stylesheets/styles.css
- src/assets/scss/modules/mot/partials/_moth.scss
Updated asset path in MOTH-only stylesheet to match new dir name on server
> Update moth paths

- src/server/views/prototypes/first-use-date/index.njk
- src/server/views/prototypes/first-use-date/v3/from-date.njk
- src/server/views/prototypes/first-use-date/v3/pre-date.njk
> Content change. Added punchline to the heading

- src/server/views/prototypes/first-use-date/index.njk
- src/server/views/prototypes/first-use-date/v4/from-date.njk
- src/server/views/prototypes/first-use-date/v4/pre-date.njk
> Added version 4 - content change

- src/server/views/prototypes/compare-tests/index.njk
- src/server/views/prototypes/compare-tests/v5/index.njk
- src/server/views/prototypes/compare-tests/v6/assess-difference-defect-1.njk
- src/server/views/prototypes/compare-tests/v6/assess-difference-defect-2.njk
- src/server/views/prototypes/compare-tests/v6/assess-difference-defect-3.njk
- src/server/views/prototypes/compare-tests/v6/assess-difference-odometer.njk
- src/server/views/prototypes/compare-tests/v6/case-summary.njk
- src/server/views/prototypes/compare-tests/v6/check-answers.njk
- src/server/views/prototypes/compare-tests/v6/compare-defects.njk
- src/server/views/prototypes/compare-tests/v6/compare-odometer-mark-difference.njk
- src/server/views/prototypes/compare-tests/v6/compare-odometer-marked.njk
- src/server/views/prototypes/compare-tests/v6/compare-odometer.njk
- src/server/views/prototypes/compare-tests/v6/index.njk
- src/server/views/prototypes/compare-tests/v6/saved.njk
- src/server/views/prototypes/compare-tests/v6/site-issues.njk
- src/server/views/prototypes/compare-tests/v6/summary.njk
> Added version 6 of test comparison

- src/server/views/prototypes/mot-history-data/cvs-v3/download-certificate-fail.njk
- src/server/views/prototypes/mot-history-data/cvs-v3/download-certificate.njk
- src/server/views/prototypes/mot-history-data/cvs-v3/history-results-audi-error1.njk
- src/server/views/prototypes/mot-history-data/cvs-v3/history-results-audi-error2.njk
- src/server/views/prototypes/mot-history-data/cvs-v3/history-results-audi.njk
> content update

- src/assets/scss/development/modules/_modules.scss
- src/assets/scss/development/modules/app-related-content/app-related-content.scss
- src/server/views/prototypes/mot-location/v2/ats-euro/index.njk
- src/server/views/prototypes/mot-location/v2/halfords/index.njk
- src/server/views/prototypes/mot-location/v2/index.njk
- src/server/views/prototypes/mot-location/v2/mr-clutch/index.njk
- src/server/views/prototypes/mot-location/v2/postcode-search.njk
- src/server/views/prototypes/mot-location/v2/results-list.njk
- src/server/views/prototypes/mot-location/v2/results-maps.njk
> Location proto css

- src/server/views/prototypes/mot-history-data/index.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/download-certificate-fail.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/download-certificate.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/enter-v5c-error.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/enter-v5c-fail.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/enter-v5c.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/enter-vrm-cvs.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/enter-vrm.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/history-results-audi.njk
- src/server/views/prototypes/mot-history-data/v5c-cert/index.njk
> design preference added for certificate on moth prototype

- composer.json
>   "version": "1.3.16"

- src/server/views/prototypes/authentication/forced-update-v1/SQ/index.njk
- src/server/views/prototypes/authentication/forced-update-v1/first-sq.njk
- src/server/views/prototypes/authentication/forced-update-v1/forced-update.njk
- src/server/views/prototypes/authentication/index.njk
- src/server/views/prototypes/authentication/special-notice-v1/2FA/first-sq.njk
- src/server/views/prototypes/authentication/special-notice-v1/2FA/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/can-not-update.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/index.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/confirmation.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/first-sq.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/inbox.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/index.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/review-new-sq.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/second-sq.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/third-sq.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/update-sq.njk
- src/server/views/prototypes/authentication/special-notice-v2/2FA/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v2/SQ/can-not-update.njk
- src/server/views/prototypes/authentication/special-notice-v2/SQ/inbox.njk
- src/server/views/prototypes/authentication/special-notice-v2/SQ/index.njk
- src/server/views/prototypes/authentication/special-notice-v2/SQ/review-new-sq.njk
- src/server/views/prototypes/authentication/special-notice-v2/SQ/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v2/answer-sq.njk
- src/server/views/prototypes/authentication/special-notice-v2/enter-pin.njk
- src/server/views/prototypes/authentication/special-notice-v2/index.njk
- src/server/views/prototypes/authentication/special-notice-v2/sign-in-success.njk
- src/server/views/prototypes/authentication/special-notice-v2/sign-in-w-sq.njk
> 2fa updates

- src/server/views/prototypes/authentication/forced-update-v1/SQ/index.njk
- src/server/views/prototypes/authentication/forced-update-v1/first-sq.njk
- src/server/views/prototypes/authentication/forced-update-v1/review-sq.njk
- src/server/views/prototypes/authentication/forced-update-v1/update-sq.njk
- src/server/views/prototypes/authentication/index.njk
- src/server/views/prototypes/authentication/special-notice-v1/2FA/first-sq.njk
- src/server/views/prototypes/authentication/special-notice-v1/2FA/review-new-sq.njk
- src/server/views/prototypes/authentication/special-notice-v1/2FA/update-sq.njk
- src/server/views/prototypes/authentication/special-notice-v1/2FA/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/can-not-update.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/you-need-to-update.njk
> Text changes and small changes

- src/server/views/prototypes/authentication/forced-update-v1/SQ/index.njk
- src/server/views/prototypes/authentication/forced-update-v1/first-sq.njk
- src/server/views/prototypes/authentication/forced-update-v1/forced-update.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/can-not-update.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/you-need-to-update.njk
> Content design changes

- src/server/views/prototypes/authentication/special-notice-v1/2FA/first-sq.njk
- src/server/views/prototypes/authentication/special-notice-v1/2FA/you-need-to-update.njk
> 2 fa update 2

- src/server/views/prototypes/authentication/special-notice-v1/2FA/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v1/SQ/you-need-to-update.njk
> content change on special notice

- src/server/views/prototypes/authentication/forced-update-v3/SQ/index.njk
- src/server/views/prototypes/authentication/forced-update-v3/confirmation.njk
- src/server/views/prototypes/authentication/forced-update-v3/enter-pin.njk
- src/server/views/prototypes/authentication/forced-update-v3/first-sq.njk
- src/server/views/prototypes/authentication/forced-update-v3/forced-update.njk
- src/server/views/prototypes/authentication/forced-update-v3/index.njk
- src/server/views/prototypes/authentication/forced-update-v3/review-sq.njk
- src/server/views/prototypes/authentication/forced-update-v3/update-sq.njk
- src/server/views/prototypes/authentication/index.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/confirmation.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/first-sq.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/inbox.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/index.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/review-new-sq.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/update-sq.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v3/SQ/can-not-update.njk
- src/server/views/prototypes/authentication/special-notice-v3/SQ/inbox.njk
- src/server/views/prototypes/authentication/special-notice-v3/SQ/index.njk
- src/server/views/prototypes/authentication/special-notice-v3/SQ/review-new-sq.njk
- src/server/views/prototypes/authentication/special-notice-v3/SQ/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v3/answer-sq.njk
- src/server/views/prototypes/authentication/special-notice-v3/enter-pin.njk
- src/server/views/prototypes/authentication/special-notice-v3/index.njk
- src/server/views/prototypes/authentication/special-notice-v3/sign-in-success.njk
- src/server/views/prototypes/authentication/special-notice-v3/sign-in-w-sq.njk
> 2 fa iteration 2

- src/server/views/prototypes/authentication/forced-update-v3/SQ/index.njk
- src/server/views/prototypes/authentication/forced-update-v3/first-sq.njk
- src/server/views/prototypes/authentication/forced-update-v3/forced-update.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/first-sq.njk
- src/server/views/prototypes/authentication/special-notice-v3/2FA/you-need-to-update.njk
- src/server/views/prototypes/authentication/special-notice-v3/SQ/you-need-to-update.njk
> special notice update

- src/server/views/prototypes/authentication/index.njk
> start page for MFA

- composer.json
> version 1.3.17

- composer.json
- composer.lock
Bump the composer version - turns out this is required too 😢
> Bump `composer.json` to 1.6.0

- composer.json
- composer.lock
- package-lock.json
- package.json
> Bump moment.js version to fix CVE
